Feat/bcr 209 tip sgx
capsule-corp-ternoa/ternoa-proposals pull request #37
Opened 2022-11-15 00:58 UTC by tapiocaboy

2022-11-15 08:29 UTC, peshwar9 reviewed
@tapiocaboy : 
1. For `register enclave`, shouldn't we also pass the RA report as a parameter, in addition to the uri?
2. For `update_enclave` , `unassign_enclave` , `change_enclave_owner` : we should pass cluster id and enclave id
3. How can we find out how many enclaves have been registered in a cluster?

2022-11-15 09:08 UTC, zorvan commented on TIPs/tip-800-SGX.md
> +  register_enclave(origin: OriginFor<T>, api_uri: TextFormat)
How to remove/unregister an enclave from blockchain totally? Because Assign/Unassign are cluster-wise operations.

2022-11-15 11:41 UTC, M2613 requested changes

2022-11-15 11:41 UTC, M2613 commented on TIPs/tip-800-SGX.md
> +| Author(s)      | Tapioca Boy |
@tapiocaboy remove this part and fill the section above the title 🙂

2022-11-16 08:27 UTC, peshwar9 reviewed
Additional changes needed in sgx pallet :
1) - Add extrinsic to register Enclave technology provider  (eg Intel)
2) Add extrinsic to register public key for sgx tech provider.
3) Add an extrinsic to register SGX enclave operator

3) During register_enclave, verify the following:

- The report was signed by SGX tech provider public key (eg Intel public key)
- The report confirms that the enclave is running on certified hardware
- The report is sent from the registered sgx operator.
- 
Open items to be decided:
1) Do we need to store the entire ias report or just a hash of it.
2) Any other verification to be performed on the ias report.
3) In future sgx provider registrations may require CAPS to be staked. All rewards and penalties will be associated with this account.
4) Should we store IAS report on IPFS and IPFS hash on chain?

2022-12-08 06:57 UTC, peshwar9 approved these changes

2022-12-14 11:52 UTC, M2613 approved these changes

2022-12-15 03:18 UTC, peshwar9 approved these changes

2022-12-15 03:19 UTC, peshwar9 approved these changes

2022-12-15 03:19 UTC, peshwar9 approved these changes

2022-12-15 03:20 UTC, peshwar9 commented
Interfaces finalized for TEE pallet.

2022-12-15 03:21 UTC, merged